server:
  port: 8085
spring:
  datasource:
    url: jdbc:h2:./devdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      javax:
        persistence:
          validation:
            mode=none: